spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_bus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # Max connections in the pool

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Options: none, update, create, create-drop
    show-sql: true  # Log SQL queries
    properties:
      hibernate:
        format_sql: true  # Pretty-print SQL logs

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    timeout: 60000 # 60 seconds
